name: FacePass

options:
  bundleIdPrefix: tech.houarimed
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    PRODUCT_BUNDLE_IDENTIFIER: tech.houarimed.facepass
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    ENABLE_BITCODE: "NO"
    ONLY_ACTIVE_ARCH: "NO"
    GENERATE_INFOPLIST_FILE: "NO"
    DEVELOPMENT_TEAM: "8RSCHWPSQP"

targets:
  FacePass:
    type: application
    platform: iOS

    sources:
      - path: Forbes_Selfie/App
      - path: Forbes_Selfie/Resources
        excludes:
          - "Info.plist"
          - "*.js"
      - path: Forbes_Selfie/Views
      - path: Forbes_Selfie/ViewModels
      - path: Forbes_Selfie/Browser
      - path: Forbes_Selfie/Services

    resources:
      - path: Forbes_Selfie/Assets.xcassets
      - path: Forbes_Selfie/Resources/content.js
      - path: Forbes_Selfie/Resources/liveness.js

    info:
      path: Forbes_Selfie/Resources/Info.plist

    settings:
      base:
        PRODUCT_NAME: FacePass
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
        DEVELOPMENT_TEAM: "8RSCHWPSQP"
